### ISSUE TITLE
Issue with initialize 'q's

### ISSUE THREAD

**Issue by ricardoavelino** [compas-dev/compas_ags#1]
The q's are initialized before devo and slsqp solver by stored attribute 'q' of the form. This is crashing here for a fresh form - with no 'q's assigned.

https://github.com/compas-dev/compas_ags/blob/af6dc7233cc76e44710a7bb4751a885d0b87ca1c/src/compas_ags/ags/loadpath3.py#L178

**Comment by andrewtliew** [comment]
This should be resolved when a **FormDiagram** is used as the input, as it by default has edge attribute ``'q'`` as 1. This is not the case with the base **Network**.
