### ISSUE TITLE
Force Diagram issues

### ISSUE THREAD

**Issue by ricardoavelino** [compas-dev/compas_ags#6]
https://github.com/compas-dev/compas_ags/blob/f50259bc35ec76946867b595f8c80cdce0213ab6/src/compas_ags/diagrams/forcediagram.py#L49

> Change:
> network_find_faces(formdiagram, formdiagram.leaves())
For:
> network_find_faces(formdiagram, formdiagram.breakpoints())

As in compas_tna to generate the dual? Otherwise when generating the faces with formdiagram.leaves() delete the exterior face using face_network.delete_face(0)

**Comment by andrewtliew** [comment]
Did you and Tom resolve this? Can the issue be closed?

**Comment by brgcode** [comment]
many things have been updated since then. please check if the issue still exists...

**Comment by ricardoavelino** [comment]
Yes it is solved but probably not implemented. I would have to check.

Ricardo Maia Avelino

On Jul 20, 2018, at 10:58, Andrew Liew <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you and Tom resolve this? Can the issue be closed?
