### ISSUE TITLE
angle measuring error

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas_ags#9]
**please revise:**
a   = [angle_vectors_xy(uv[i], _uv[i]) for i in range(len(edges))]
**to:**
a   = [angle_vectors_xy(uv[i], _uv[i], deg=True) for i in range(len(edges))]

**_otherwise, flipped edges are not properly accounted for in:_**
    for u, v, attr in form.edges(True):
        e = uv_e[(u, v)]
        attr['l'] = l[e, 0]
        attr['a'] = a[e]
        if a[e] < 90:
            attr['f'] = _l[e, 0]
            attr['q'] = q[e, 0]
        else:
            attr['f'] = - _l[e, 0]
            attr['q'] = - q[e, 0]

**Comment by brgcode** [comment]
solved in 52fa2af
